In [1]:
import pandas as pd
import numpy as np

In [2]:
#import librarries
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM, Dropout

In [3]:
from sklearn.preprocessing import MinMaxScaler

In [4]:
#read train and test
path = "C:/Users/mayur/Downloads/ongc_train.csv"
traindata = pd.read_csv(path)
len(traindata)


2233

In [5]:
path = "C:/Users/mayur/Downloads/ongc_test.csv"
testdata = pd.read_csv(path)
testdata

date    open    high     low   close         wap  no_of_shares  \
0    01-Jan-19  150.60  150.60  148.50  148.95  149.446169        206090   
1    02-Jan-19  148.30  148.30  146.30  147.60  147.305830        491473   
2    03-Jan-19  145.15  145.55  141.80  143.20  143.871101       4943024   
3    04-Jan-19  142.00  146.20  141.70  145.65  144.982979        372189   
4    07-Jan-19  148.00  148.00  145.95  147.55  146.952427        440062   
..         ...     ...     ...     ...     ...         ...           ...   
240  24-Dec-19  125.00  126.60  124.65  126.00  126.037164        199063   
241  26-Dec-19  126.85  129.45  124.55  128.05  126.803369        405800   
242  27-Dec-19  129.15  129.80  127.20  128.40  128.402356        288717   
243  30-Dec-19  128.40  129.20  127.20  127.95  128.157624        154323   
244  31-Dec-19  127.95  129.25  127.50  128.75  128.544834        158230   

     trades   turnover  deliverables  spread_h_l  spread_c_o  
0      1373   30799361         82710        2.10       -1.65  
1      3192   72396838        153732        2.00       -0.70  
2      4828  711158303       1284188        3.75       -1.95  
3      2470   53961070         90215        4.50        3.65  
4      2404   64668179         80781        2.05       -0.45  
..      ...        ...           ...         ...         ...  
240    1326   25089336         54415        1.95        1.00  
241    2754   51456807        110602        4.90        1.20  
242    2057   37071943         71721        2.60       -0.75  
243    1507   19777669         52349        2.00       -0.45  
244    1369   20339649         41961        1.75        0.80  

[245 rows x 12 columns]

In [6]:
#predict the close price ]
#take the columns as ' close' from both train and test datasets
traindata = traindata.iloc[:,4:5].values
traindata

array([[1187.3 ],
       [1208.  ],
       [1221.3 ],
       ...,
       [ 149.2 ],
       [ 150.45],
       [ 150.2 ]])

In [7]:
testdata = testdata.iloc[:,4:5].values

In [8]:
print(len(traindata)),print(len(testdata))

2233
245


(None, None)

In [9]:
#standardize the train and test datasets
minmax = MinMaxScaler()
train_scaled = minmax.fit_transform(traindata)
test_scaled = minmax.fit_transform(testdata)

In [10]:
#verify the transformation
print(train_scaled)

[[0.79534179]
 [0.81102064]
 [0.82109449]
 ...
 [0.00905132]
 [0.00999811]
 [0.00980875]]


In [11]:
print(test_scaled)

[[0.53768844]
 [0.51507538]
 [0.44137353]
 [0.48241206]
 [0.51423786]
 [0.51172529]
 [0.48073702]
 [0.44723618]
 [0.46649916]
 [0.44639866]
 [0.47319933]
 [0.48827471]
 [0.47319933]
 [0.49246231]
 [0.46733668]
 [0.46231156]
 [0.44137353]
 [0.42127303]
 [0.42378559]
 [0.41959799]
 [0.4078727 ]
 [0.38107203]
 [0.41624791]
 [0.42211055]
 [0.49413735]
 [0.43383585]
 [0.49916248]
 [0.51926298]
 [0.44639866]
 [0.37102178]
 [0.34589615]
 [0.28056951]
 [0.25544389]
 [0.30569514]
 [0.33919598]
 [0.37102178]
 [0.45561139]
 [0.50502513]
 [0.53098827]
 [0.52596315]
 [0.51675042]
 [0.52345059]
 [0.53517588]
 [0.53936348]
 [0.63819095]
 [0.63316583]
 [0.5921273 ]
 [0.55695142]
 [0.60552764]
 [0.5921273 ]
 [0.54857621]
 [0.57788945]
 [0.64991625]
 [0.63400335]
 [0.67252931]
 [0.58626466]
 [0.59798995]
 [0.69765494]
 [0.71021776]
 [0.72696817]
 [0.67169179]
 [0.71524288]
 [0.68425461]
 [0.680067  ]
 [0.64991625]
 [0.64154104]
 [0.66331658]
 [0.69095477]
 [0.68174204]
 [0.68425461]
 [0.69849246]
 [0.68

In [12]:
print(traindata[2000:])

[[194.05]
 [193.6 ]
 [199.95]
 [207.15]
 [210.5 ]
 [208.25]
 [204.95]
 [203.8 ]
 [203.35]
 [195.1 ]
 [192.45]
 [188.85]
 [185.65]
 [189.8 ]
 [188.55]
 [187.75]
 [190.85]
 [185.85]
 [188.4 ]
 [186.6 ]
 [184.95]
 [187.  ]
 [190.1 ]
 [186.2 ]
 [190.  ]
 [190.75]
 [188.4 ]
 [188.5 ]
 [189.55]
 [185.5 ]
 [185.25]
 [180.95]
 [180.15]
 [179.65]
 [183.65]
 [183.4 ]
 [180.6 ]
 [181.5 ]
 [177.4 ]
 [176.6 ]
 [174.1 ]
 [175.45]
 [178.7 ]
 [177.25]
 [178.65]
 [179.6 ]
 [177.8 ]
 [180.  ]
 [177.7 ]
 [175.55]
 [177.15]
 [176.9 ]
 [178.4 ]
 [180.1 ]
 [181.7 ]
 [181.4 ]
 [182.5 ]
 [181.5 ]
 [180.8 ]
 [181.8 ]
 [183.15]
 [182.35]
 [180.9 ]
 [182.6 ]
 [179.55]
 [181.15]
 [180.75]
 [180.5 ]
 [179.7 ]
 [180.7 ]
 [180.3 ]
 [183.6 ]
 [182.95]
 [182.9 ]
 [188.15]
 [187.3 ]
 [187.45]
 [188.75]
 [187.05]
 [188.75]
 [185.05]
 [185.6 ]
 [184.3 ]
 [175.55]
 [167.65]
 [175.35]
 [175.95]
 [175.45]
 [173.95]
 [177.35]
 [172.95]
 [171.25]
 [171.15]
 [170.35]
 [172.7 ]
 [173.5 ]
 [173.25]
 [171.35]
 [170.  ]
 [168.5 ]


In [13]:
#set the lags(timestamp) for RNN
timestamp = 30


In [14]:
#build the trainx and trainy datasets
#create the empty lists
trainx=[]; trainy=[]


In [15]:
for i in range(timestamp,len(train_scaled)):
    trainx.append(train_scaled[i-timestamp:i,0])
    trainy.append(train_scaled[i,0])
    

In [18]:
len(trainx[0])

30

In [17]:
trainy[0]

0.7308085589850406

In [19]:
trainx[1]

array([0.81102064, 0.82109449, 0.82234425, 0.81757243, 0.81662564,
       0.79878811, 0.80143912, 0.828025  , 0.81495929, 0.81439121,
       0.80344632, 0.77697406, 0.75951524, 0.74046582, 0.74387427,
       0.73686802, 0.73027836, 0.72906646, 0.730089  , 0.73220981,
       0.75432683, 0.75913653, 0.71993941, 0.72505207, 0.74016285,
       0.73406552, 0.71993941, 0.72936944, 0.72035599, 0.73080856])

In [20]:
#change the trainx/trainy properties  to match the RNN format
trainx = np.array(trainx)
trainy = np.array(trainy)
trainx

array([[0.79534179, 0.81102064, 0.82109449, ..., 0.71993941, 0.72936944,
        0.72035599],
       [0.81102064, 0.82109449, 0.82234425, ..., 0.72936944, 0.72035599,
        0.73080856],
       [0.82109449, 0.82234425, 0.81757243, ..., 0.72035599, 0.73080856,
        0.72864988],
       ...,
       [0.01458057, 0.01779966, 0.01639841, ..., 0.00855899, 0.00802878,
        0.00719561],
       [0.01779966, 0.01639841, 0.01461844, ..., 0.00802878, 0.00719561,
        0.00905132],
       [0.01639841, 0.01461844, 0.01298996, ..., 0.00719561, 0.00905132,
        0.00999811]])

In [21]:
#reshape the trainx to convert it into a tensor
trainx = np.reshape(trainx,(trainx.shape[0],trainx.shape[1],1))
trainx.shape

(2203, 30, 1)

In [22]:
trainx[0]

array([[0.79534179],
       [0.81102064],
       [0.82109449],
       [0.82234425],
       [0.81757243],
       [0.81662564],
       [0.79878811],
       [0.80143912],
       [0.828025  ],
       [0.81495929],
       [0.81439121],
       [0.80344632],
       [0.77697406],
       [0.75951524],
       [0.74046582],
       [0.74387427],
       [0.73686802],
       [0.73027836],
       [0.72906646],
       [0.730089  ],
       [0.73220981],
       [0.75432683],
       [0.75913653],
       [0.71993941],
       [0.72505207],
       [0.74016285],
       [0.73406552],
       [0.71993941],
       [0.72936944],
       [0.72035599]])

In [23]:
#build the network
reg = Sequential()
reg.add(LSTM(units=32,return_sequences=True,input_shape=(trainx.shape[1],1)))

In [24]:
(trainx.shape[1],1)

(30, 1)

In [25]:
reg.add(Dropout(0.2))

In [26]:
#LSTM Layer2
reg.add(LSTM(units=32,return_sequences=True))
reg.add(Dropout(0.2))

In [27]:
#LSTM Layer3
reg.add(LSTM(units=32,return_sequences=True))
reg.add(Dropout(0.2))

In [28]:
#LSTM Layer4 ->stock back
reg.add(LSTM(units=32))
reg.add(Dropout(0.2))

In [29]:
#output layer
reg.add(Dense(units=1))

In [32]:
#compile the network
reg.compile(optimizer='adam',loss='mean_squared_error')

In [33]:
#train the model on the train data
reg.fit(trainx,trainy,epochs=20,batch_size=10)

Epoch 1/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0083
Epoch 2/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0049
Epoch 3/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0042
Epoch 4/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0035
Epoch 5/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0037
Epoch 6/20
221/221 [==============================] - 6s 28ms/step - loss: 0.0029
Epoch 7/20
221/221 [==============================] - 6s 28ms/step - loss: 0.0027
Epoch 8/20
221/221 [==============================] - 6s 28ms/step - loss: 0.0026
Epoch 9/20
221/221 [==============================] - 6s 27ms/step - loss: 0.0024
Epoch 10/20
221/221 [==============================] - 6s 29ms/step - loss: 0.0026
Epoch 11/20
221/221 [==============================] - 6s 29ms/step - loss: 0.0025
Epoch 12/20
221/221 [==============================] - 6s 28ms/step - loss: 0.0025
Epoch 13/20
2

# READ AGAIN

In [34]:
path = "C:/Users/mayur/Downloads/ongc_train.csv"
train = pd.read_csv(path)
len(train)


2233

In [36]:
path = "C:/Users/mayur/Downloads/ongc_test.csv"
test = pd.read_csv(path)
test

date    open    high     low   close         wap  no_of_shares  \
0    01-Jan-19  150.60  150.60  148.50  148.95  149.446169        206090   
1    02-Jan-19  148.30  148.30  146.30  147.60  147.305830        491473   
2    03-Jan-19  145.15  145.55  141.80  143.20  143.871101       4943024   
3    04-Jan-19  142.00  146.20  141.70  145.65  144.982979        372189   
4    07-Jan-19  148.00  148.00  145.95  147.55  146.952427        440062   
..         ...     ...     ...     ...     ...         ...           ...   
240  24-Dec-19  125.00  126.60  124.65  126.00  126.037164        199063   
241  26-Dec-19  126.85  129.45  124.55  128.05  126.803369        405800   
242  27-Dec-19  129.15  129.80  127.20  128.40  128.402356        288717   
243  30-Dec-19  128.40  129.20  127.20  127.95  128.157624        154323   
244  31-Dec-19  127.95  129.25  127.50  128.75  128.544834        158230   

     trades   turnover  deliverables  spread_h_l  spread_c_o  
0      1373   30799361         82710        2.10       -1.65  
1      3192   72396838        153732        2.00       -0.70  
2      4828  711158303       1284188        3.75       -1.95  
3      2470   53961070         90215        4.50        3.65  
4      2404   64668179         80781        2.05       -0.45  
..      ...        ...           ...         ...         ...  
240    1326   25089336         54415        1.95        1.00  
241    2754   51456807        110602        4.90        1.20  
242    2057   37071943         71721        2.60       -0.75  
243    1507   19777669         52349        2.00       -0.45  
244    1369   20339649         41961        1.75        0.80  

[245 rows x 12 columns]

In [38]:
#prediction on the test data 
#to build the test data we require the information of the last 'n' days (as defined in the timsestamp parameter)
#1)combine the train and test data 
totalrec = pd.concat((train.close,test.close),0)
totalrec

0      1187.30
1      1208.00
2      1221.30
3      1222.95
4      1216.65
        ...   
240     126.00
241     128.05
242     128.40
243     127.95
244     128.75
Name: close, Length: 2478, dtype: float64

In [39]:
len(train)

2233

In [40]:
len(test)

245

In [41]:
len(totalrec)

2478

In [42]:
#input data for prediction
inputs = len(totalrec)-len(test)-timestamp
inputs

2203

In [44]:
inputs = totalrec[len(totalrec)-len(test)-timestamp:].values
inputs

array([156.55, 154.4 , 152.6 , 151.75, 152.2 , 146.75, 146.3 , 142.65,
       140.75, 140.2 , 142.6 , 146.2 , 143.7 , 140.15, 139.9 , 137.25,
       138.35, 141.65, 143.25, 146.95, 148.35, 147.9 , 148.45, 148.65,
       148.55, 147.85, 146.75, 149.2 , 150.45, 150.2 , 148.95, 147.6 ,
       143.2 , 145.65, 147.55, 147.4 , 145.55, 143.55, 144.7 , 143.5 ,
       145.1 , 146.  , 145.1 , 146.25, 144.75, 144.45, 143.2 , 142.  ,
       142.15, 141.9 , 141.2 , 139.6 , 141.7 , 142.05, 146.35, 142.75,
       146.65, 147.85, 143.5 , 139.  , 137.5 , 133.6 , 132.1 , 135.1 ,
       137.1 , 139.  , 144.05, 147.  , 148.55, 148.25, 147.7 , 148.1 ,
       148.8 , 149.05, 154.95, 154.65, 152.2 , 150.1 , 153.  , 152.2 ,
       149.6 , 151.35, 155.65, 154.7 , 157.  , 151.85, 152.55, 158.5 ,
       159.25, 160.25, 156.95, 159.55, 157.7 , 157.45, 155.65, 155.15,
       156.45, 158.1 , 157.55, 157.7 , 158.55, 157.8 , 156.55, 160.45,
       160.2 , 157.75, 163.95, 168.7 , 168.4 , 168.15, 169.3 , 169.35,
      

In [45]:
len(inputs)

275

In [48]:
inputs.shape

(275,)

In [49]:
#convert the inputs into numpy array and rescale
inputs = inputs.reshape(-1,1)
inputs.shape


(275, 1)

In [50]:
inputs = minmax.fit_transform(inputs)
inputs

array([[0.66499162],
       [0.62897822],
       [0.59882747],
       [0.58458961],
       [0.5921273 ],
       [0.50083752],
       [0.49329983],
       [0.4321608 ],
       [0.40033501],
       [0.39112228],
       [0.43132328],
       [0.49162479],
       [0.44974874],
       [0.39028476],
       [0.38609715],
       [0.34170854],
       [0.360134  ],
       [0.41541039],
       [0.44221106],
       [0.5041876 ],
       [0.52763819],
       [0.5201005 ],
       [0.52931323],
       [0.53266332],
       [0.53098827],
       [0.51926298],
       [0.50083752],
       [0.54187605],
       [0.56281407],
       [0.55862647],
       [0.53768844],
       [0.51507538],
       [0.44137353],
       [0.48241206],
       [0.51423786],
       [0.51172529],
       [0.48073702],
       [0.44723618],
       [0.46649916],
       [0.44639866],
       [0.47319933],
       [0.48827471],
       [0.47319933],
       [0.49246231],
       [0.46733668],
       [0.46231156],
       [0.44137353],
       [0.421

In [51]:
#create the testx data for predictions
testx = []
for i in range(timestamp,len(inputs)):
    testx.append(inputs[i-timestamp:i,0])
    
print(testx)   

[array([0.66499162, 0.62897822, 0.59882747, 0.58458961, 0.5921273 ,
       0.50083752, 0.49329983, 0.4321608 , 0.40033501, 0.39112228,
       0.43132328, 0.49162479, 0.44974874, 0.39028476, 0.38609715,
       0.34170854, 0.360134  , 0.41541039, 0.44221106, 0.5041876 ,
       0.52763819, 0.5201005 , 0.52931323, 0.53266332, 0.53098827,
       0.51926298, 0.50083752, 0.54187605, 0.56281407, 0.55862647]), array([0.62897822, 0.59882747, 0.58458961, 0.5921273 , 0.50083752,
       0.49329983, 0.4321608 , 0.40033501, 0.39112228, 0.43132328,
       0.49162479, 0.44974874, 0.39028476, 0.38609715, 0.34170854,
       0.360134  , 0.41541039, 0.44221106, 0.5041876 , 0.52763819,
       0.5201005 , 0.52931323, 0.53266332, 0.53098827, 0.51926298,
       0.50083752, 0.54187605, 0.56281407, 0.55862647, 0.53768844]), array([0.59882747, 0.58458961, 0.5921273 , 0.50083752, 0.49329983,
       0.4321608 , 0.40033501, 0.39112228, 0.43132328, 0.49162479,
       0.44974874, 0.39028476, 0.38609715, 0.34170854, 0.

In [52]:
testx[0]

array([0.66499162, 0.62897822, 0.59882747, 0.58458961, 0.5921273 ,
       0.50083752, 0.49329983, 0.4321608 , 0.40033501, 0.39112228,
       0.43132328, 0.49162479, 0.44974874, 0.39028476, 0.38609715,
       0.34170854, 0.360134  , 0.41541039, 0.44221106, 0.5041876 ,
       0.52763819, 0.5201005 , 0.52931323, 0.53266332, 0.53098827,
       0.51926298, 0.50083752, 0.54187605, 0.56281407, 0.55862647])

In [53]:
#change the trainx/trainy properties  to match the RNN format
testx = np.array(testx)
print(testx)
#reshape the testx to convert it into a tensor
testx = np.reshape(testx,(testx.shape[0],testx.shape[1],1))
print(testx.shape)


[[0.66499162 0.62897822 0.59882747 ... 0.54187605 0.56281407 0.55862647]
 [0.62897822 0.59882747 0.58458961 ... 0.56281407 0.55862647 0.53768844]
 [0.59882747 0.58458961 0.5921273  ... 0.55862647 0.53768844 0.51507538]
 ...
 [0.32495812 0.31323283 0.28559464 ... 0.13065327 0.15326633 0.18760469]
 [0.31323283 0.28559464 0.27303183 ... 0.15326633 0.18760469 0.19346734]
 [0.28559464 0.27303183 0.28140704 ... 0.18760469 0.19346734 0.18592965]]
(245, 30, 1)


In [54]:
testx[0]

array([[0.66499162],
       [0.62897822],
       [0.59882747],
       [0.58458961],
       [0.5921273 ],
       [0.50083752],
       [0.49329983],
       [0.4321608 ],
       [0.40033501],
       [0.39112228],
       [0.43132328],
       [0.49162479],
       [0.44974874],
       [0.39028476],
       [0.38609715],
       [0.34170854],
       [0.360134  ],
       [0.41541039],
       [0.44221106],
       [0.5041876 ],
       [0.52763819],
       [0.5201005 ],
       [0.52931323],
       [0.53266332],
       [0.53098827],
       [0.51926298],
       [0.50083752],
       [0.54187605],
       [0.56281407],
       [0.55862647]])

In [55]:
#predict the 'close' price of the stock using the model
pred = reg.predict(testx)
print(pred)

[[0.5141156 ]
 [0.521224  ]
 [0.5233262 ]
 [0.5130788 ]
 [0.4979021 ]
 [0.48766184]
 [0.48517233]
 [0.48556882]
 [0.48246306]
 [0.4770959 ]
 [0.46965313]
 [0.46430498]
 [0.46394253]
 [0.4662876 ]
 [0.4708705 ]
 [0.47374916]
 [0.4731232 ]
 [0.46761596]
 [0.45705545]
 [0.44452602]
 [0.43285644]
 [0.4228742 ]
 [0.41270018]
 [0.40593243]
 [0.40429473]
 [0.41352803]
 [0.42552334]
 [0.4404878 ]
 [0.45813483]
 [0.46831673]
 [0.46104962]
 [0.43720126]
 [0.39955842]
 [0.3554049 ]
 [0.31868064]
 [0.2994774 ]
 [0.30076054]
 [0.32408285]
 [0.3650269 ]
 [0.41374707]
 [0.45778716]
 [0.48832095]
 [0.5043819 ]
 [0.5103849 ]
 [0.5113045 ]
 [0.5206736 ]
 [0.53880465]
 [0.5557826 ]
 [0.5629184 ]
 [0.5657434 ]
 [0.5666833 ]
 [0.56276566]
 [0.5585044 ]
 [0.5640068 ]
 [0.57689464]
 [0.595795  ]
 [0.6064966 ]
 [0.6074695 ]
 [0.6128772 ]
 [0.626489  ]
 [0.6460368 ]
 [0.6596914 ]
 [0.6691789 ]
 [0.672317  ]
 [0.6703203 ]
 [0.6627483 ]
 [0.6520031 ]
 [0.644125  ]
 [0.64410233]
 [0.6494195 ]
 [0.65670884]
 [0.66

In [57]:
#convert the predictions into its actual form and convert to a list 
pred = minmax.inverse_transform(pred)
pred = np.round(pred.tolist(),2)
pred

array([[147.3 ],
       [147.89],
       [147.89],
       [147.3 ],
       [146.7 ],
       [146.1 ],
       [146.1 ],
       [146.1 ],
       [145.51],
       [145.51],
       [144.91],
       [144.31],
       [144.31],
       [144.91],
       [144.91],
       [144.91],
       [144.91],
       [144.91],
       [144.31],
       [143.12],
       [142.52],
       [141.92],
       [141.33],
       [141.33],
       [140.73],
       [141.33],
       [142.52],
       [143.12],
       [144.31],
       [144.91],
       [144.31],
       [143.12],
       [140.73],
       [138.34],
       [135.95],
       [134.76],
       [134.76],
       [135.95],
       [138.94],
       [141.33],
       [144.31],
       [146.1 ],
       [146.7 ],
       [147.3 ],
       [147.3 ],
       [147.89],
       [149.09],
       [150.28],
       [150.28],
       [150.88],
       [150.88],
       [150.28],
       [150.28],
       [150.28],
       [151.48],
       [152.67],
       [153.27],
       [153.27],
       [153.27

In [71]:
np.ravel(pred)

array([147.3 , 147.89, 147.89, 147.3 , 146.7 , 146.1 , 146.1 , 146.1 ,
       145.51, 145.51, 144.91, 144.31, 144.31, 144.91, 144.91, 144.91,
       144.91, 144.91, 144.31, 143.12, 142.52, 141.92, 141.33, 141.33,
       140.73, 141.33, 142.52, 143.12, 144.31, 144.91, 144.31, 143.12,
       140.73, 138.34, 135.95, 134.76, 134.76, 135.95, 138.94, 141.33,
       144.31, 146.1 , 146.7 , 147.3 , 147.3 , 147.89, 149.09, 150.28,
       150.28, 150.88, 150.88, 150.28, 150.28, 150.28, 151.48, 152.67,
       153.27, 153.27, 153.27, 154.46, 155.66, 156.25, 156.85, 156.85,
       156.85, 156.25, 155.66, 155.06, 155.06, 155.66, 156.25, 156.25,
       156.85, 156.85, 156.85, 157.45, 157.45, 158.04, 159.83, 161.62,
       163.42, 164.01, 165.21, 165.21, 165.8 , 165.8 , 166.4 , 166.4 ,
       165.8 , 164.61, 164.01, 162.82, 162.82, 163.42, 164.61, 167.  ,
       168.79, 169.98, 169.98, 169.98, 169.98, 169.39, 168.19, 168.19,
       168.19, 168.19, 167.6 , 167.  , 166.4 , 165.8 , 165.8 , 166.4 ,
      

In [70]:
test.loc[:,'close']

0      148.95
1      147.60
2      143.20
3      145.65
4      147.55
        ...  
240    126.00
241    128.05
242    128.40
243    127.95
244    128.75
Name: close, Length: 245, dtype: float64

In [69]:
#create the dataframe to store actual and predicted data
df=pd.DataFrame({'actual':test.close,'predicted':np.ravel(pred)})
df

actual  predicted
0    148.95     147.30
1    147.60     147.89
2    143.20     147.89
3    145.65     147.30
4    147.55     146.70
..      ...        ...
240  126.00     125.21
241  128.05     125.21
242  128.40     125.21
243  127.95     125.80
244  128.75     126.40

[245 rows x 2 columns]

In [73]:
#calculate the MSE of the predictions
from sklearn.metrics import mean_squared_error
mse1 = mean_squared_error(df.actual,df.predicted)
print("MSE = {}, RMSE = {}".format(round(mse1,3),round(np.sqrt(mse1),3)))

MSE = 19.634, RMSE = 4.431
